language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
#  - "3.4" #itk 5.0.1 does not run with this version
#  - "3.5" # fstring not available with this version
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - ITK_VERSION=5.0.0
  - ITK_VERSION=5.0.1
jobs:
  exclude:
    - python: "3.8"
      env: ITK_VERSION=5.0.0
install:
  - pip install -q itk==$ITK_VERSION
  - pip install -e .
script: 
  - python -m unittest gatetools -v
  - python -m unittest gatetools.phsp -v

notifications:
  email: false